#pragma once

// ============================================================================
// tokenizer.h — Minimal BPE Tokenizer for Llama 3 / tiktoken-style models
//
// Loads vocabulary and merge rules from a .forge.vocab file (generated by
// convert.py alongside the .forge weights file).
//
// Encoding:  text → UTF-8 bytes → regex pretokenize → BPE merges → token IDs
// Decoding:  token ID → vocab lookup → bytes → UTF-8 string
//
// The .forge.vocab file format:
//   Line 1:       vocab_size (uint32)
//   Line 2:       n_merges (uint32)
//   Lines 3..V+2: id<TAB>base64(token_bytes)
//   Lines V+3..:  id1<SPACE>id2   (merge pairs, in priority order)
//
// Usage:
//   Tokenizer tok;
//   tok.load("model.forge.vocab");
//   auto ids = tok.encode("Hello world");
//   std::string text = tok.decode(ids);
// ============================================================================

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <utility>

namespace transformer {

// ============================================================================
// Base64 decode (for vocab entries)
// ============================================================================
static const uint8_t b64_table[256] = {
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,62,64,64,64,63,
    52,53,54,55,56,57,58,59,60,61,64,64,64, 0,64,64,
    64, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,
    15,16,17,18,19,20,21,22,23,24,25,64,64,64,64,64,
    64,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,
    41,42,43,44,45,46,47,48,49,50,51,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
    64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
};

static std::string base64_decode(const std::string& encoded) {
    std::string out;
    out.reserve(encoded.size() * 3 / 4);
    uint32_t buf = 0;
    int bits = 0;
    for (char c : encoded) {
        uint8_t val = b64_table[static_cast<uint8_t>(c)];
        if (val == 64) continue;  // skip padding '='
        buf = (buf << 6) | val;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push_back(static_cast<char>((buf >> bits) & 0xFF));
        }
    }
    return out;
}

static std::string base64_encode(const std::string& data) {
    static const char b64[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::string out;
    out.reserve((data.size() + 2) / 3 * 4);
    uint32_t buf = 0;
    int bits = 0;
    for (uint8_t c : data) {
        buf = (buf << 8) | c;
        bits += 8;
        while (bits >= 6) {
            bits -= 6;
            out.push_back(b64[(buf >> bits) & 0x3F]);
        }
    }
    if (bits > 0) {
        out.push_back(b64[(buf << (6 - bits)) & 0x3F]);
        while (out.size() % 4) out.push_back('=');
    }
    return out;
}

// ============================================================================
// Tokenizer
// ============================================================================
class Tokenizer {
public:
    // Special token IDs (set during load)
    int32_t bos_id = -1;
    int32_t eos_id = -1;

    bool load(const std::string& vocab_path) {
        std::ifstream f(vocab_path);
        if (!f.is_open()) {
            fprintf(stderr, "ERROR: Cannot open vocab file: %s\n", vocab_path.c_str());
            return false;
        }

        // Line 1: vocab_size
        uint32_t vocab_size, n_merges;
        f >> vocab_size >> n_merges;
        f.ignore(256, '\n');

        printf("  Loading tokenizer: %u tokens, %u merges\n", vocab_size, n_merges);

        // Lines: id<TAB>base64(token_bytes)
        // First pass: read all entries, track max ID
        std::vector<std::pair<uint32_t, std::string>> entries;
        entries.reserve(vocab_size);
        uint32_t max_id = 0;
        for (uint32_t i = 0; i < vocab_size; i++) {
            std::string line;
            std::getline(f, line);
            size_t tab = line.find('\t');
            if (tab == std::string::npos) {
                fprintf(stderr, "ERROR: Bad vocab line %u: %s\n", i, line.c_str());
                return false;
            }
            uint32_t id = std::stoul(line.substr(0, tab));
            std::string b64 = line.substr(tab + 1);
            std::string token_bytes = base64_decode(b64);
            entries.push_back({id, token_bytes});
            if (id > max_id) max_id = id;
        }

        // Allocate to fit the largest ID
        id_to_token_.resize(max_id + 1);
        for (auto& [id, token_bytes] : entries) {
            id_to_token_[id] = token_bytes;
            token_to_id_[token_bytes] = id;
        }

        // Build byte-to-token-ID mapping
        // For each single-byte token in the vocab, record its ID
        byte_to_id_.resize(256, UINT32_MAX);
        uint32_t actual_size = static_cast<uint32_t>(id_to_token_.size());
        for (uint32_t i = 0; i < actual_size; i++) {
            const auto& tok = id_to_token_[i];
            if (tok.size() == 1) {
                uint8_t byte = static_cast<uint8_t>(tok[0]);
                if (byte_to_id_[byte] == UINT32_MAX) {
                    byte_to_id_[byte] = i;
                }
            }
        }

        // Count how many byte tokens were found
        int byte_count = 0;
        for (int i = 0; i < 256; i++) {
            if (byte_to_id_[i] != UINT32_MAX) byte_count++;
        }
        printf("  Byte tokens mapped: %d/256", byte_count);
        if (byte_count > 0) {
            // Print a few examples
            printf(" (e.g. 'H'=%u", byte_to_id_['H']);
            printf(", 'e'=%u", byte_to_id_['e']);
            printf(", ' '=%u)", byte_to_id_[' ']);
        }
        printf("\n");

        // Merge rules: id1<SPACE>id2 (priority = line order)
        merges_.reserve(n_merges);
        for (uint32_t i = 0; i < n_merges; i++) {
            uint32_t a, b;
            f >> a >> b;
            auto key = merge_key(a, b);
            merge_priority_[key] = i;
            // The merged result is the concatenation of token bytes
            std::string merged = id_to_token_[a] + id_to_token_[b];
            auto it = token_to_id_.find(merged);
            if (it != token_to_id_.end()) {
                merge_result_[key] = it->second;
            }
            merges_.push_back({a, b});
        }

        // Detect special tokens
        // DeepSeek uses fullwidth ｜ (U+FF5C, UTF-8: EF BD 9C) and ▁ (U+2581, UTF-8: E2 96 81)
        // We build the expected strings at runtime to avoid NVCC char range issues
        std::string ds_bos = "<";
        ds_bos += '\xef'; ds_bos += '\xbd'; ds_bos += '\x9c';  // ｜
        ds_bos += "begin";
        ds_bos += '\xe2'; ds_bos += '\x96'; ds_bos += '\x81';  // ▁
        ds_bos += "of";
        ds_bos += '\xe2'; ds_bos += '\x96'; ds_bos += '\x81';  // ▁
        ds_bos += "text";
        ds_bos += '\xef'; ds_bos += '\xbd'; ds_bos += '\x9c';  // ｜
        ds_bos += ">";

        std::string ds_eos = "<";
        ds_eos += '\xef'; ds_eos += '\xbd'; ds_eos += '\x9c';  // ｜
        ds_eos += "end";
        ds_eos += '\xe2'; ds_eos += '\x96'; ds_eos += '\x81';  // ▁
        ds_eos += "of";
        ds_eos += '\xe2'; ds_eos += '\x96'; ds_eos += '\x81';  // ▁
        ds_eos += "sentence";
        ds_eos += '\xef'; ds_eos += '\xbd'; ds_eos += '\x9c';  // ｜
        ds_eos += ">";

        for (uint32_t i = 0; i < vocab_size; i++) {
            const auto& tok = id_to_token_[i];
            // BOS tokens (in priority order)
            if (tok == "<|begin_of_text|>") bos_id = i;         // Llama 3
            else if (tok == ds_bos) bos_id = i;                  // DeepSeek
            else if (tok == "<s>" && bos_id < 0) bos_id = i;    // Llama 2, Mistral

            // EOS tokens (in priority order)
            if (tok == "<|end_of_text|>") eos_id = i;            // Llama 3
            else if (tok == ds_eos) { eos_id = i; }              // DeepSeek
            else if (tok == "<|endoftext|>" && eos_id < 0) eos_id = i;  // Qwen, GPT
            else if (tok == "</s>" && eos_id < 0) eos_id = i;    // Llama 2, Mistral
        }

        // Override from model config if provided (more reliable than string matching)
        // This is done in main after loading config, but print what we found here
        printf("  BOS=%d, EOS=%d\n", bos_id, eos_id);
        return true;
    }

    // ========================================================================
    // Encode: text → token IDs
    //
    // 1. Convert text to UTF-8 bytes
    // 2. Start with each byte as its own token ID (byte 0x00..0xFF = ID 0..255)
    // 3. Repeatedly merge the highest-priority adjacent pair until no more merges
    // ========================================================================
    std::vector<int32_t> encode(const std::string& text, bool add_bos = true) const {
        std::vector<int32_t> ids;
        if (add_bos && bos_id >= 0) {
            ids.push_back(bos_id);
        }

        if (text.empty()) return ids;

        // Pretokenize: split on whitespace boundaries and punctuation
        // Simplified regex matching tiktoken's pattern for Llama 3:
        //   (?i:'s|'t|'re|'ve|'m|'ll|'d)
        //   |[^\r\n\p{L}\p{N}]?\p{L}+
        //   |\p{N}{1,3}
        //   | ?[^\s\p{L}\p{N}]+[\r\n]*
        //   |\s*[\r\n]+
        //   |\s+(?!\S)
        //   |\s+
        //
        // For simplicity, we split on spaces, keeping the leading space
        // as part of the token (tiktoken behavior). This matches the common
        // case; a full regex implementation would be needed for perfect
        // compatibility with special punctuation patterns.

        std::vector<std::string> words = pretokenize(text);

        for (const auto& word : words) {
            // Convert each word to byte-level token IDs
            std::vector<uint32_t> word_ids;

            // First, check if the whole word is in vocab (tiktoken's ignore_merges)
            auto it = token_to_id_.find(word);
            if (it != token_to_id_.end()) {
                ids.push_back(static_cast<int32_t>(it->second));
                continue;
            }

            // Start with individual bytes mapped to their vocab IDs
            for (uint8_t byte : word) {
                uint32_t id = byte_to_id_[byte];
                if (id == UINT32_MAX) {
                    // Byte not in vocab — shouldn't happen with a proper BPE vocab
                    // Fall back to raw byte value
                    id = static_cast<uint32_t>(byte);
                }
                word_ids.push_back(id);
            }

            // Apply BPE merges greedily
            bpe_merge(word_ids);

            for (auto id : word_ids) {
                ids.push_back(static_cast<int32_t>(id));
            }
        }

        return ids;
    }

    // ========================================================================
    // Decode: token IDs → text
    // ========================================================================
    std::string decode(const std::vector<int32_t>& ids) const {
        std::string out;
        for (auto id : ids) {
            if (id < 0 || id >= static_cast<int32_t>(id_to_token_.size())) continue;
            // Skip special tokens in output
            const auto& tok = id_to_token_[id];
            if (!tok.empty() && tok[0] == '<' && tok.back() == '>') continue;
            out += tok;
        }
        return out;
    }

    // Decode a single token
    std::string decode_token(int32_t id) const {
        if (id < 0 || id >= static_cast<int32_t>(id_to_token_.size())) return "";
        return id_to_token_[id];
    }

    int32_t vocab_size() const { return static_cast<int32_t>(id_to_token_.size()); }

private:
    std::vector<std::string> id_to_token_;
    std::unordered_map<std::string, uint32_t> token_to_id_;
    std::vector<uint32_t> byte_to_id_;  // byte value → token ID

    struct MergePair { uint32_t a, b; };
    std::vector<MergePair> merges_;
    std::unordered_map<uint64_t, uint32_t> merge_priority_;  // key → priority
    std::unordered_map<uint64_t, uint32_t> merge_result_;    // key → merged ID

    static uint64_t merge_key(uint32_t a, uint32_t b) {
        return (static_cast<uint64_t>(a) << 32) | b;
    }

    // ========================================================================
    // BPE merge: repeatedly find the highest-priority pair and merge
    // ========================================================================
    void bpe_merge(std::vector<uint32_t>& ids) const {
        while (ids.size() >= 2) {
            // Find the pair with lowest priority number (= highest priority)
            uint32_t best_priority = UINT32_MAX;
            size_t best_idx = SIZE_MAX;
            uint32_t best_result = 0;

            for (size_t i = 0; i < ids.size() - 1; i++) {
                auto key = merge_key(ids[i], ids[i+1]);
                auto pit = merge_priority_.find(key);
                if (pit != merge_priority_.end() && pit->second < best_priority) {
                    auto rit = merge_result_.find(key);
                    if (rit != merge_result_.end()) {
                        best_priority = pit->second;
                        best_idx = i;
                        best_result = rit->second;
                    }
                }
            }

            if (best_idx == SIZE_MAX) break;  // No more merges possible

            // Apply the merge
            ids[best_idx] = best_result;
            ids.erase(ids.begin() + best_idx + 1);
        }
    }

    // ========================================================================
    // Pretokenize: split text into words (simplified tiktoken-style)
    // Keeps leading spaces attached to the following word.
    // ========================================================================
    static std::vector<std::string> pretokenize(const std::string& text) {
        std::vector<std::string> words;
        std::string current;

        for (size_t i = 0; i < text.size(); i++) {
            char c = text[i];

            if (c == ' ' || c == '\t' || c == '\n' || c == '\r') {
                // Whitespace: if we have accumulated chars, flush them
                if (!current.empty()) {
                    words.push_back(current);
                    current.clear();
                }
                // Start new word with the whitespace char
                current.push_back(c);
            } else {
                current.push_back(c);
            }
        }
        if (!current.empty()) {
            words.push_back(current);
        }

        return words;
    }
};

} // namespace transformer
